export enum PasswordCriteriaErrorsEnum {
  TOO_SHORT = "TOO_SHORT",
  TOO_LONG = "TOO_LONG",
  INVALID_UPPERCASE = "INVALID_UPPERCASE",
  INVALID_LOWERCASE = "INVALID_LOWERCASE",
  INVALID_DIGITS = "INVALID_DIGITS",
  INVALID_SPECIAL_CHARS = "INVALID_SPECIAL_CHARS"
}